const sidebar = {
  "/base/nginx/": [
    "1.index",
    "1.config",
    "2.static",
    "3.cdn",
    "4.cache",
    "5.cors",
    "6.link",
    "7.module",
    "8.project",
    "9.utils",
    "10.ui",
    '11.data',
    // '12.skill',
    // '13.com',
    // '14.data',
    // '15.api'
  ],
    "/base/config/": [
    "1.index",
    "1.config",
    "2.static",
    "3.cdn",
    "4.cache",
    "5.cors",
    "6.link",
    "7.module",
    "8.project",
    "9.utils",
    "10.ui",
    '11.data',
    // '12.skill',
    // '13.com',
    // '14.data',
    // '15.api'
  ],
  "/senior/use/": [
    "1.index",
    "2.extend",
    "3.config",
    "4.render",
    "5.api",
    "6.form",
    "7.checkBox",
    "8.active",
    "9.alert",
    "10.table",
    "11.tree",
  ],
};
module.exports = sidebar;
